rehlds/engine/host.cpp, rehlds/engine/info.cpp, rehlds/engine/sv_main.cpp
Two bugs and two improvements.
=> Some bugfixes and improvements

rehlds/engine/net_chan.cpp
Read more here: https://github.com/ValveSoftware/halflife/issues/1425#issuecomment-45697889
=> Fixed download bug (creating directory bug)

rehlds/common/IGameServerData.h, rehlds/engine/sv_remoteaccess.cpp
=> Fixed #6: Exposed IGameServerData interface

rehlds/engine/decals.cpp, rehlds/engine/host_cmd.cpp, rehlds/engine/net_chan.cpp, rehlds/engine/wad.cpp
Fixed the computation of cpuPercent
Made signature checks (bz2, wad3) look more beatiful
=> Function Host_UpdateStats on Linux doesn't work correctly.

rehlds/build.gradle, rehlds/engine/pmovetst.cpp, rehlds/engine/pmovetst.h, rehlds/engine/world.cpp, rehlds/engine/world.h
Unrolled tail recursion in RecursiveHullCheck
=> Unrolled tail recursion in RecursiveHullCheck

rehlds/engine/mathlib.cpp, rehlds/engine/mathlib_e.h, rehlds/engine/pmovetst.cpp, rehlds/engine/pr_cmds.cpp, rehlds/engine/sys_dll2.cpp, rehlds/engine/world.cpp, rehlds/engine/world.h, rehlds/public/rehlds/crc32.cpp, rehlds/public/rehlds/sys_shared.cpp, rehlds/public/rehlds/sys_shared.h
Added SSE 4.1 implementation of dot product, added SinCos function, maked fast version of SV_Move for point hull (trace line), small copying optimization in SV_RunCmd.
=> Math optimizations, faster traceline version

.gitignore, dep/cppunitlite/include/cppunitlite/Assertions.h, dep/cppunitlite/include/cppunitlite/Test.h, dep/cppunitlite/src/Assertions.cpp, msvc/ReHLDS.sln, rehlds/engine/mathlib.cpp, rehlds/msvc/ReHLDS.vcxproj, rehlds/msvc/ReHLDS.vcxproj.filters, rehlds/unittests/mathlib_tests.cpp
Mathlib unit tests
Added REHLDS_OP_PEDANTIC define to all configs in the msvc project
Fixed CrossProduct
=> Mathlib unit tests

rehlds/engine/delta.cpp, rehlds/engine/delta_jit.cpp, rehlds/engine/delta_jit.h, rehlds/engine/sv_main.cpp, rehlds/msvc/ReHLDS.vcxproj
JITted DELTA_CountSendFields
Use JITted delta in DELTA_CheckDelta
=> JITted DELTA_CountSendFields

rehlds/engine/delta.cpp, rehlds/engine/delta.h, rehlds/engine/delta_jit.cpp, rehlds/engine/delta_jit.h, rehlds/engine/sv_main.cpp, rehlds/unittests/delta_tests.cpp
DELTA_SetSendFlagBits implemented in JIT.
Using bit masks instead of flags to mark sending fields.
Updated delta unit tests.
Some optimizations in JIT code.
=> Finished work with JIT in DELTA_CheckDelta and DELTA_WriteDelta

rehlds/engine/delta_jit.cpp, rehlds/engine/delta_jit.h, rehlds/engine/sv_main.cpp, rehlds/public/rehlds/osconfig.h, rehlds/unittests/delta_tests.cpp
Delta encoder tests: refactoring
Added prefetches to delta and deltaJit
=> Delta encoder tests: refactoring

rehlds/engine/common.cpp, rehlds/engine/delta.cpp, rehlds/engine/delta_jit.cpp, rehlds/engine/delta_jit.h, rehlds/engine/server.h, rehlds/engine/sv_main.cpp, rehlds/engine/world.cpp, rehlds/unittests/delta_tests.cpp
Maked test for DELTA_TestDelta.
Markbits aligned to 16.
Unrolled tail recursion in SV_FindTouchedLeafs and SV_LinkContents.
Other small optimizations and fixes.
=> JITted DELTA_TestDelta.

build.gradle, buildSrc/build.gradle, gradle/wrapper/gradle-wrapper.properties, rehlds/build.gradle, shared_icc.gradle
Updated gradle to 2.4
Updated gradle-cpp-plugin to 1.2
=> Fixed #28: Link libstdc++ statically on linux

rehlds/engine/cl_null.cpp, rehlds/engine/cmd.cpp, rehlds/engine/common.cpp, rehlds/engine/crc.cpp, rehlds/engine/cvar.cpp, rehlds/engine/delta.cpp, rehlds/engine/host.cpp, rehlds/engine/info.cpp, rehlds/engine/l_studio.cpp, rehlds/engine/mathlib.cpp, rehlds/engine/mathlib_e.h, rehlds/engine/mem.cpp, rehlds/engine/model.cpp, rehlds/engine/net_ws.cpp, rehlds/engine/pmove.cpp, rehlds/engine/pmovetst.cpp, rehlds/engine/pr_cmds.cpp, rehlds/engine/pr_edict.cpp, rehlds/engine/r_studio.cpp, rehlds/engine/sv_main.cpp, rehlds/engine/sv_move.cpp, rehlds/engine/sv_steam3.cpp, rehlds/engine/sv_user.cpp, rehlds/engine/sys_dll.cpp, rehlds/engine/tmessage.cpp, rehlds/engine/zone.cpp, rehlds/public/rehlds/osconfig.h, rehlds/rehlds/rehlds_api_impl.cpp, rehlds/rehlds/rehlds_interfaces_impl.cpp
All functions that could be called from outside must realign the stack
Removed NOINLINE from MSG_Write*Bits functions since stack alignment issue is resolved
=> Fixed #40 :all functions that could be called from outside must realign the stack

rehlds/engine/sv_main.cpp
If connecting two players at one time - see screenshot
=> Fix bug with SV_CheckForDuplicateNames

rehlds/engine/sv_main.cpp
HLSW and some other software doesn't support negative challenge values.
=> Fixed bug in challenge generator.

rehlds/engine/sv_main.cpp, rehlds/engine/unicode_strtools.cpp
Added iswprint check in Q_IsUnprintableW function
Added Q_StripUnprintableAndSpace function using for player name
=> Unicode fixes

rehlds/engine/cmd.cpp, rehlds/engine/net_ws.cpp, rehlds/engine/sv_main.cpp, rehlds/engine/sv_steam3.cpp, rehlds/engine/sv_user.cpp, rehlds/public/rehlds/hookchains.h, rehlds/public/rehlds/rehlds_api.h, rehlds/public/rehlds/rehlds_interfaces.h, rehlds/rehlds/hookchains_impl.cpp, rehlds/rehlds/hookchains_impl.h, rehlds/rehlds/rehlds_api_impl.cpp, rehlds/rehlds/rehlds_api_impl.h, rehlds/rehlds/rehlds_interfaces_impl.cpp, rehlds/rehlds/rehlds_interfaces_impl.h, rehlds/unittests/crc32c_tests.cpp, rehlds/unittests/mathlib_tests.cpp
HookChains refactoring.
Added API functions for getting all net message buffers.
Added callback for file hash checking.
Fixed tests passing if sse 4+ doesn't supported.
=> HookChains refactoring

rehlds/engine/net_ws.cpp, rehlds/engine/server.h, rehlds/engine/sv_main.cpp, rehlds/public/rehlds/userid_rehlds.h, rehlds/unittests/crc32c_tests.cpp
=> PreprocessPacket hook moved after IP ban check

rehlds/engine/host_cmd.cpp, rehlds/engine/net_ws.cpp, rehlds/engine/net_ws.h, rehlds/engine/server.h, rehlds/engine/sv_main.cpp, rehlds/engine/sv_user.cpp, rehlds/public/rehlds/rehlds_api.h, rehlds/rehlds/rehlds_security.cpp, rehlds/rehlds/rehlds_security.h
Fixed const qualifiers in sdk
Exported sv_version cvar
=> Fixed stringcmd flood

rehlds/engine/unicode_strtools.cpp
Added Q_UTF8ToUTF32, Q_UTF32ToUTF8
Cleanup unicode_strtools.cpp
=> Fix linux unicode in nickname

rehlds/engine/sys_dll.cpp
Added missing EXT_FUNC for Con_DPrintf
=> Fix crash Con_DPrintf at linux

rehlds/engine/host.cpp, rehlds/engine/sv_main.cpp, rehlds/engine/unicode_strtools.cpp, rehlds/engine/world.cpp, rehlds/engine/world.h
Added Q_iswprint
Added cvar sv_force_ent_intersection for to bypass condition check with SOILID_SLIDEBOX and forced call SV_CheckSphereIntersection
=> Changed version in Host_Version at rehlds_fixes

rehlds/engine/cmd.cpp
=> Fix: not read configuration the files at rehlds_fixes

rehlds/build.gradle, rehlds/engine/pr_edict.cpp, rehlds/public/rehlds/common_rehlds.h, rehlds/rehlds/hookchains_impl.h
Removed rtti
Reduced MAX_HOOKS_IN_CHAIN value
=> Fixed loading of maps without world classname or with long list of wads

rehlds/engine/common.cpp, rehlds/engine/common.h, rehlds/engine/ed_strpool.cpp, rehlds/engine/filesystem.cpp, rehlds/engine/filesystem_internal.cpp, rehlds/engine/host.cpp, rehlds/engine/host_cmd.cpp, rehlds/engine/model.cpp, rehlds/engine/net_chan.cpp, rehlds/engine/net_ws.cpp, rehlds/engine/pr_cmds.cpp, rehlds/engine/sv_main.cpp, rehlds/engine/sv_steam3.cpp, rehlds/engine/sys_dll.cpp, rehlds/engine/sys_dll2.cpp, rehlds/engine/textures.cpp, rehlds/engine/tmessage.cpp, rehlds/engine/zone.cpp, rehlds/msvc/ReHLDS.vcxproj, rehlds/rehlds/FlightRecorderImpl.cpp, rehlds/rehlds/hookchains_impl.cpp, rehlds/rehlds/rehlds_security.cpp
Added prefix Q_* for functions strlen/strcmp/strpcy/memset/memcpy/memmove etc.
Added for solution configuration (Debug Swds Play/Release Swds Play) the path to libacof32.lib in linker.
=> Cut of nicknames '+' if next there is something digit or alphanumeric character.

rehlds/engine/sv_phys.cpp
https://github.com/dreamstalker/rehlds/issues/92
=> Fixed typo in SV_RunThink

rehlds/engine/client.h, rehlds/engine/com_custom.cpp, rehlds/engine/server.h, rehlds/engine/sv_main.cpp, rehlds/engine/sv_user.cpp
Fix for:
- correctly using types with define
- missing EXT_FUNC for SV_GetChallenge
=> Fix: types

rehlds/engine/sv_main.cpp, rehlds/engine/sv_user.cpp, rehlds/public/rehlds/rehlds_api.h, rehlds/public/rehlds/rehlds_interfaces.h, rehlds/rehlds/rehlds_api_impl.cpp, rehlds/rehlds/rehlds_api_impl.h, rehlds/rehlds/rehlds_interfaces_impl.cpp, rehlds/rehlds/rehlds_interfaces_impl.h
- Added functions SV_AddResource, SetNumConsistency, GetNumConsistency for ReHLDS API.
- Changed name GenericFileConsistencyResponce to CheckConsistencyResponce.
=> ReHLDS API: Added some functions

rehlds/common/const.h, rehlds/common/qlimits.h, rehlds/common/quakedef.h, rehlds/engine/consistency.h, rehlds/engine/filter.h, rehlds/engine/info.h, rehlds/engine/net.h, rehlds/engine/pr_cmds.cpp, rehlds/engine/server.h, rehlds/engine/sv_main.cpp, rehlds/engine/sys_dll.cpp, rehlds/msvc/ReHLDS.vcxproj, rehlds/msvc/ReHLDS.vcxproj.filters, rehlds/public/rehlds/common_rehlds.h, rehlds/public/rehlds/custom.h, rehlds/public/rehlds/rehlds_api.h, rehlds/public/rehlds/rehlds_interfaces.h, rehlds/rehlds/rehlds_api_impl.cpp, rehlds/rehlds/rehlds_api_impl.h, rehlds/rehlds/rehlds_interfaces_impl.cpp, rehlds/rehlds/rehlds_interfaces_impl.h
ReHLDS API: Implemented SV_ActivateServer hook and added GetResourcesNum, GetDecalNameNum
Fix: using defines instead of magic numbers
Added include qlimits.h
Reduced the size global variable localinfo, ipfilters, userfilters
=> ReHLDS API: Implemented SV_ActivateServer hook

rehlds/engine/hashpak.cpp, rehlds/engine/net_ws.cpp, rehlds/engine/sv_user.cpp, rehlds/engine/sv_user.h, rehlds/public/tier0/platform_win32.cpp, rehlds/rehlds/platform.cpp, rehlds/rehlds/platform.h
Some fixes in usercmd parsing code
=> Fixed some issues found by Coverity

rehlds/common/mathlib.h, rehlds/engine/common.cpp, rehlds/engine/host.cpp, rehlds/engine/net_ws.cpp, rehlds/engine/sv_main.cpp, rehlds/public/basetypes.h, rehlds/public/rehlds/osconfig.h
Using inline algorithms instead of defines
=> Fixed crash on bot disconnect

rehlds/engine/host.cpp, rehlds/engine/sv_user.cpp, rehlds/rehlds/rehlds_security.cpp
Fixed bug with angles on dying
=> Increased move command burst rate

rehlds/engine/delta_jit.cpp, rehlds/engine/delta_jit.h
=> Fixed DELTAJIT_MAX_FIELDS limit check

rehlds/engine/delta_jit.cpp, rehlds/engine/sv_main.cpp, rehlds/engine/sv_steam3.cpp, rehlds/engine/tmessage.cpp, rehlds/engine/unicode_strtools.cpp, rehlds/public/rehlds/rehlds_api.h, rehlds/rehlds/rehlds_api_impl.cpp, rehlds/rehlds/rehlds_api_impl.h
Refactoring in SV_ExtractFrom
Added Steam_GSBUpdateUserData hook
Refactored and optimized calculateBytecount without hardcode
=> Fixed crash in Q_UnicodeConvertT

rehlds/engine/decals.cpp, rehlds/engine/sv_main.cpp, rehlds/public/rehlds/rehlds_api.h, rehlds/rehlds/rehlds_api_impl.h
=> Fixed userid serialization hook

rehlds/engine/decals.cpp, rehlds/engine/sv_main.cpp
=> Corrected fix in Decal_Init

rehlds/engine/pr_cmds.cpp, rehlds/engine/sys_dll.cpp
rehlds should export pfnEngCheckParm in engfuncs
=> export EngCheckParm

rehlds/engine/pr_cmds.cpp
=> Added preventing twice resource precache in SV_CreateGenericResources… (#130)

rehlds/engine/pr_cmds.cpp
=> Added preventing twice resource precache in PF_precache_generic_I (#130)

rehlds/engine/common.cpp
=> Fixed MSG_WriteBitString (bug with non-ASCII chars) (#150)

rehlds/engine/cmd.cpp
=> Fixed commands with unicode (#152)

rehlds/engine/sv_main.cpp
=> Added replacing escape sequences in kick reason (#154)

rehlds/engine/pr_cmds.cpp, rehlds/engine/server.h, rehlds/engine/sv_main.cpp, rehlds/engine/sv_user.cpp, rehlds/rehlds/rehlds_interfaces_impl.cpp
Extended max generic resource count to 4096
Added backward slash replace in PF_precache_generic_I
Removed local copying in SV_CreateGenericResources
Added moving checked resources to first positions in resource list
=> Extended max resource count to 4096

rehlds/engine/pr_cmds.cpp, rehlds/engine/server.h, rehlds/engine/sv_main.cpp
Added cvar sv_auto_precache_sounds_in_models
Moved models auto precache code to SV_ActivateServer
=> Added auto precache sounds in models (event 5004)

rehlds/engine/filter.h, rehlds/engine/sv_main.cpp
Fixed invalid mask in StringToFilter for A.B.0.D, A.0.B.D etc.
Added ban time validation in addip
Added optional argument for removeip: removeAll to remove all filters that input filter includes
Added optional argument for listip: ipaddress to show filters which it includes
=> Added CIDR support for addip, removeip, listip

rehlds/engine/sv_main.cpp
Added bantime in kick reason in banid and addip
=> Fixed assertion with enabled debug (isctype)

rehlds/engine/common.cpp, rehlds/engine/filesystem_internal.cpp, rehlds/engine/hashpak.cpp, rehlds/engine/sys_dll2.cpp
Fixed #114
Fixed some decompile mistakes
Fixed FS_Read and FS_Write
=> Fixed reading and writing custom.hpk (Fixed #114)

rehlds/engine/server.h, rehlds/engine/sv_main.cpp, rehlds/engine/sv_upld.cpp, rehlds/engine/sv_user.cpp
=> Added sv_delayed_spray_upload cvar (#173)

rehlds/engine/net.h, rehlds/engine/net_chan.cpp, rehlds/engine/server.h, rehlds/engine/sv_main.cpp, rehlds/engine/sv_user.cpp
Fixed mistake in Netchan_CreateFileFragmentsFromBuffer (fixed customization downloading)
Added sv_rehlds_force_dlmax cvar (also for #173)
Corrected FRAGMENT_MAX_SIZE value
#114 fully fixed
I believe now all bugs with sprays are fixed.
=> Fixed MAX_FRAGMENTS value for customizations (#114 now really fixed)

rehlds/engine/sv_main.cpp, rehlds/engine/textures.cpp
Moved auto WAD precaching to TEX_InitFromWad
=> Added auto precaching detail textures if present

rehlds/engine/sv_user.cpp
I accidentally found this while reading code.
P.S. The most useful commit, lol. :D
=> Remove useless assignment in pmove

rehlds/build.gradle, rehlds/engine/common.h, rehlds/engine/mathlib.cpp, rehlds/engine/mathlib_e.h, rehlds/engine/sv_phys.cpp
Removed some unnecessary checks for windows dll
=> Small update in sse math

README.md, rehlds/common/const.h, rehlds/engine/server.h, rehlds/engine/sv_main.cpp, rehlds/public/rehlds/rehlds_api.h, rehlds/rehlds/rehlds_api_impl.cpp, rehlds/rehlds/rehlds_api_impl.h
Added direct call for functions SV_EmitSound2 and SV_StartSound
Added cvar sv_rcon_condebug 0/1
=> Implemented new function SV_EmitSound2 for 3-rd things and hook.

rehlds/engine/net.h, rehlds/engine/server.h, rehlds/engine/sv_main.cpp, rehlds/public/rehlds/rehlds_api.h, rehlds/rehlds/rehlds_api_impl.cpp
=> Added SV_UpdateUserInfo to API

build.gradle, rehlds/build.gradle
Added new task buildFixes for fast and simply building project.
Example: "gradlew --max-workers=1 clean buildFixes"
=> Allow to build project outside of the git repository.

README.md, flightrec/decoder/src/main/java/org/rehlds/flightrec/filescan/FlightRecFileScanner.java
Added info in Readme.md about faster building.
=> Fix flight decoder are failed.

rehlds/rehlds/rehlds_security.cpp
Could we get something like this in the next build?
=> Cvars for command flood punishments

rehlds/engine/sv_main.cpp
Simplified USERID copying
Corrected buffer displacement when element is removed
Fixed idstring fix =/
Fixed reverse-engineering mistake with numeration in listid (should start from 1)
=> RemoveId and ListId fixes

rehlds/engine/unicode_strtools.cpp
http://unicode-table.com/ru/3000/
=> Fix non-printable space character (0x3000)

rehlds/engine/host.cpp, rehlds/engine/host_cmd.cpp, rehlds/engine/pr_cmds.cpp, rehlds/engine/sv_main.cpp
Global reliable net buffer is deprecated now
Need tests
=> Re-fixed hung players #103 and early TeamScore #113 bugs

rehlds/engine/server.h, rehlds/engine/sv_main.cpp
https://github.com/WPMGPRoSToTeMa/PatchedGoldSrcClient/issues/7
=> Fixed animation speed when player has attached entities

rehlds/engine/common.cpp, rehlds/engine/crc.cpp, rehlds/engine/decals.cpp, rehlds/engine/filesystem_internal.cpp, rehlds/engine/filesystem_internal.h, rehlds/engine/host.cpp, rehlds/engine/host_cmd.cpp, rehlds/engine/model.cpp, rehlds/engine/net_chan.cpp, rehlds/engine/pr_cmds.cpp, rehlds/engine/r_studio.cpp, rehlds/engine/sv_main.cpp, rehlds/engine/sv_move.cpp, rehlds/engine/sv_phys.cpp, rehlds/engine/sys_dll.cpp, rehlds/engine/sys_dll.h, rehlds/engine/sys_dll2.cpp, rehlds/engine/sys_dll2.h, rehlds/engine/tmessage.cpp, rehlds/engine/wad.cpp, rehlds/engine/world.cpp, rehlds/engine/zone.cpp, rehlds/hookers/6132_hooker.cpp
Add NOXREFCHECK to all function, marked as NOXREF.
=> Nohref checks

rehlds/engine/server.h, rehlds/engine/sv_main.cpp
I found a comment
`// TODO: make one global var with mods enum.`
So, now it's done.)
=> Convert g_bIs#GameName# to enum.

rehlds/engine/sv_main.cpp, rehlds/engine/sys_dll.cpp
=> Fix and optimize file extension checks

rehlds/engine/server.h, rehlds/engine/sv_main.cpp
=> Allowed spectator and global unreliable buffer to overflow

rehlds/engine/hashpak.cpp, rehlds/engine/net_chan.cpp, rehlds/engine/sv_main.cpp
I think it's more flexible way.
=> Use __func__ whenever possible

rehlds/engine/delta.cpp, rehlds/engine/delta_jit.cpp, rehlds/engine/mathlib.cpp, rehlds/hookers/6132_hooker.cpp, rehlds/unittests/delta_tests.cpp, rehlds/unittests/unicode_tests.cpp
@LevShisterov, this also requires review. thanks :)
=> MSVC Warning Fix (v140_xp)

rehlds/engine/net_ws.cpp, rehlds/engine/net_ws.h
=> Refactoring: use SOCKET type for sockets, simplified code for invalid socket value.

rehlds/engine/sv_main.cpp
Update description for 'kick' cmd.
=> Some desc added.

rehlds/engine/sv_main.cpp
* Fix nullptr dereferencing
* Remove redundant check 
* Fix comment
=> Fix IsSafeFileToDownload (thx [WPMG]PRoSToTeM@)

dep/bzip2/msvc/bzip2.vcxproj, dep/cppunitlite/msvc/cppunitlite.vcxproj, rehlds/dedicated/msvc/dedicated.vcxproj, rehlds/msvc/ReHLDS.vcxproj
Probably, VS2017 should be added here too.
=> Selecting correct toolset for VS2013/VS2015.

rehlds/dedicated/src/sys_ded.cpp, rehlds/dedicated/src/sys_linux.cpp
Optimisation in call to the sleep function.
=> Make cycle more close to original.

rehlds/engine/pr_cmds.cpp
=> Add REHLDS_FIXES checks

rehlds/engine/sys_dll2.cpp
=> Fix out of bounds assign in Sys_InitGame

rehlds/engine/delta.cpp, rehlds/engine/world.cpp
DELTA_TestDelta: reverse engineering mistake.
=> SV_RecursiveHullCheck: fix typo

rehlds/HLTV/Console/src/System.cpp, rehlds/HLTV/Core/src/Server.cpp, rehlds/HLTV/Core/src/Server.h, rehlds/HLTV/Core/src/World.cpp, rehlds/HLTV/Core/src/World.h, rehlds/HLTV/README.md
HLTV: Removed the obsolete filesystem_steam.
=> HLTV: Fix crash and small refactoring.

rehlds/HLTV/Core/src/BSPModel.cpp, rehlds/HLTV/Core/src/Server.cpp, rehlds/HLTV/DemoPlayer/src/DemoPlayer.cpp, rehlds/HLTV/DemoPlayer/src/DemoPlayer.h, rehlds/HLTV/README.md, rehlds/HLTV/common/DemoFile.cpp, rehlds/HLTV/common/DemoFile.h
=> HLTV: Some fixes and small refactoring.

README.md, rehlds/HLTV/common/net_internal.h, rehlds/engine/host_cmd.cpp, rehlds/engine/host_cmd.h, rehlds/engine/net.h, rehlds/engine/server.h, rehlds/engine/sv_main.cpp
reslist <sound | model | decal | generic | event>
rescount
=> Rework #529, #530

rehlds/engine/sv_phys.cpp, rehlds/engine/sv_phys.h
[video: movement toss](https://www.youtube.com/watch?v=54ucyS1NDWM)
=> Improve movement toss

rehlds/engine/info.cpp, rehlds/engine/sv_main.cpp
=> Fixes for new exploit involving " in info strings.

rehlds/engine/net_ws.cpp
Simplified diff:
Please test it.
=> Fixed NET_QueuePacket workflow

rehlds/engine/sv_main.cpp
=> fix buffer overflow

README.md, rehlds/engine/sv_main.cpp
I tried make entity editor with amxx, but **public pfn_keyvalue(ent)** do make impossible to edit classname of enities. 
This is very easy entity editor for any map. I don't tried add new entities, but possible need add them to end of file. File .ent created while map loading. Path /maps/mapname.ent .
Example video "how it works" on cs_assault map: https://youtu.be/Rkxcapg4rOU
_Sorry for very bad video fps, my pc 10 years old )))_
=> Simple entity editor

rehlds/HLTV/Core/src/Server.cpp, rehlds/HLTV/Core/src/Server.h, rehlds/HLTV/common/net_internal.h, rehlds/engine/net.h, rehlds/engine/pr_cmds.cpp, rehlds/engine/sv_main.cpp
=> Implement `svc_exec` support in the engine and HLTV

rehlds/dlls/player.h
This patch removes unneeded qualifier.
=> Remove unnecessary qualifier

README.md
=> add ReHLDS logo in README

rehlds/HLTV/Proxy/src/Proxy.cpp, rehlds/HLTV/Proxy/src/Proxy.h, rehlds/HLTV/Proxy/src/ProxyClient.cpp, rehlds/public/HLTV/IProxy.h
Close https://github.com/dreamstalker/rehlds/issues/744
=> Add: new chatdelay command.

rehlds/HLTV/common/mathlib.cpp
Fix for HTLV: RadiusFromBounds.
Need for #ifdef REHLDS_FIXES ??
=> HTLV: RadiusFromBounds is broken

rehlds/engine/sv_user.cpp
Small code style fix in sv_user.cpp
=> sv_user.cpp: Small code refactoring

rehlds/public/rehlds/static_map.h
**REHLDS_OPT_PEDANTIC** static_map.h fix
`if (true) {	cc |= 0x20; } `
to 
`if ( cc >= 'A' && cc <= 'Z') { cc |= 0x20;	}`
=> static_map.h: fix lowercase convert

rehlds/engine/sv_main.cpp
=> sv_main.cpp: `SV_New_f()` uses `Q_snprintf()` unsafe format.

.github/workflows/build.yml
Temporary solution for VirusTotal issues.
related #841
=> change destinition folder for linux build

rehlds/engine/unicode_strtools.cpp
=> Fixed non-printable unicode chars

README.md
to avoid https://github.com/dreamstalker/rehlds/pull/894 confusion
=> Fix incorrect cvar description: `sv_rehlds_maxclients_from_single_ip`

.github/workflows/build.yml
Reverts dreamstalker/rehlds#842
=> Revert "change destinition folder for linux build"

README.md
Closes #1020
Closes #1013
Closes #1008
Closes #999
=> Add steamcmd instructions to readme

rehlds/engine/server.h, rehlds/engine/sv_main.cpp, rehlds/public/rehlds/rehlds_api.h, rehlds/rehlds/rehlds_api_impl.cpp, rehlds/rehlds/rehlds_api_impl.h, rehlds/version/version.h
Useful to create a custom resource list when requested by a client or to allow multiple download url setup.
Misspelled SendResources with AddResources
=> Add `SV_SendResources` hook

rehlds/engine/sv_phys.cpp, rehlds/engine/sv_user.cpp
Just a parameter renamed, code is exactly the same.
=> Move SV_CheckMovingGround into SV_Physics

README.md
=> cmake dependency added

.github/workflows/build.yml
=> [chore] improved ci build and signing at release publish
