rehlds/ReHLDS

rehlds/engine/client.h, rehlds/engine/cmd.cpp, rehlds/engine/common.cpp, rehlds/engine/pr_cmds.cpp, rehlds/engine/server.h, rehlds/engine/sv_main.cpp, rehlds/engine/sv_user.cpp
Fixed some Cmd_ functions, fixed messages sending in ClientPutInServer forward, added unrolled (un)munge2 functions, added one overflow check, fixed fullupdate spam from not active clients.
=> Second part of fixes

rehlds/engine/delta.cpp, rehlds/engine/delta.h, rehlds/engine/delta_jit.cpp, rehlds/engine/delta_jit.h, rehlds/engine/sv_main.cpp, rehlds/unittests/delta_tests.cpp
Fixed #24: Remember fields unmarked by encoder and force set it if entity is used as a baseline
=> Fixed #24: Remember fields unmarked by encoder and force set it if entity is used as a baseline

rehlds/engine/host.cpp, rehlds/engine/sv_main.cpp, rehlds/engine/sv_user.cpp, rehlds/msvc/ReHLDS.vcxproj, rehlds/msvc/ReHLDS.vcxproj.filters, rehlds/rehlds/precompiled.h, rehlds/rehlds/rehlds_security.cpp, rehlds/rehlds/rehlds_security.h
Added rate limiter for client's move commands (SV_ParseMove)
Default limits are 350cmds/sec average (1.5 sec interval) and 600 cmds/sec burst (0.2 sec interval)
Client running at 100fps and cl_cmdrate 100 with ideal network connection has 100cmds/seconds rate.
In case of bad network (50% packet loss) server would execute 200cmds/sec for this player. It's pretty hard to hit the 350cmds/sec limit in normal condition.
=> Fix for the Buffer Overload 4 exploit

rehlds/engine/sv_main.cpp, rehlds/public/rehlds/rehlds_api.h, rehlds/rehlds/rehlds_api_impl.cpp, rehlds/rehlds/rehlds_api_impl.h, rehlds/rehlds/rehlds_interfaces_impl.cpp
It's my vision of callback that allows to customize sending client's userinfo. But there is a problem, if info is sent to all, for customization we must call SV_WriteFullClientUpdate individually for each client. What's better:
1) Rewrite callNext to allow call it several times from one chain.
2) Write another call next function for this situation.
3) Add api function for SV_WriteFullClientUpdate and use it instead of call next chain.
=> Implemented SV_WriteFullClientUpdate callback

rehlds/engine/common.h, rehlds/engine/sv_main.cpp, rehlds/engine/sv_user.cpp, rehlds/msvc/ReHLDS.vcxproj, rehlds/public/rehlds/eiface.h, rehlds/public/rehlds/rehlds_api.h, rehlds/rehlds/rehlds_api_impl.cpp, rehlds/rehlds/rehlds_api_impl.h
Fix: bug in SVC_GetChallenge incorrectly used format specifiers type uint64 for Linux.
Fix: spelling mistake with SV_CheckConsistencyResponce
Fix: net_from in solution project for HOOK_ENGINE
Cleanup and fix to build success for all solutions.
=> Fix: bug in SVC_GetChallenge

rehlds/engine/model.cpp
This bug can be reproduced as follows:
The presence of *.res file for the map
de_dust2.res
> /sprites/flame2.spr
thus the removal of slash's with iterator post ++ followed by a delete of the first character in pathname
result:
> prites/flame2.spr
=> Fix: bug with removing slash in the path to resources

rehlds/engine/sv_main.cpp
Fixed bug with:
> Host_Error: PF_precache_generic_I: Bad string '// .\de_storm.res - created with RESGen v1.00'
Reason: comments are doesn't ignored in .res files by reason of the signature BOM in header.
Detailed Investigation:
de_storm.res
>// .\de_storm.res - created with RESGen v1.00
// RESGen is made by Jeroen "ShadowLord" Bogers
// URL: http://www.unitedadmins.com/mapRESGEN.asp
// Res creation date, GMT timezone (dd-mm-yyyy): 08-06-2001
>
// .res entries:
de_storm.wad
[... etc]
If .res file saved with BOM signature so we get
Breakpoint from SV_CreateGenericResources:
> п»ї// .\de_storm.res - created with RESGen v1.00
where      "п»ї"    is    EF BB BF
> 0EF 0BB 0BF 047 047 032 046 092 100 101 095 115 116 111 114 109 046 114 101 115 032 045 032 099 114 101 097 116 101 100 032 119 105 …
=> Fix: skip bytes BOM signature in SV_CreateGenericResources

rehlds/engine/sv_main.cpp, rehlds/rehlds/rehlds_interfaces_impl.cpp, rehlds/rehlds/rehlds_interfaces_impl.h
Server sends TeamScore to early connection client which leads to bug in ScoreBoard CS 1.6
Fixed #103
=> Fixed #103

rehlds/engine/pr_cmds.cpp
Most of models have backward slash in seqgroups filepath
=> Fix slashes in seqgroup filename

rehlds/engine/server.h, rehlds/engine/sv_main.cpp, rehlds/engine/world.cpp
If bbox size greater than hull size:
with old code: hull is located in bbox negative corner (-x and -y).
with new code: hull is located in bbox center.
=> SV_HullForBsp: use hull center instead of corner

rehlds/engine/sv_upld.cpp
Hide unneeded checks under REHLDS_FIXES macro.
Use SV_ClearResourceLists() function instead of two SV_ClearResourceList().
Use for() on lists, instead of while(). More readable.
=> Some fixes for sv_upld.cpp

rehlds/engine/decals.cpp
Fixed decals.wad loading fallback to DEFAULTGAME directory if mod doesn't supply it (like in AG).
=> Fixed decals.wad loading fallback to DEFAULTGAME directory.

rehlds/engine/sys_dll2.cpp
VS 2013 says:
> 2>d:\rehlds\rehlds\engine\sys_dll2.cpp(196): error C4996: 'GetVersionExA': объявлен deprecate
2>          c:\program files (x86)\windows kits\8.1\include\um\sysinfoapi.h(433): см. объявление "GetVersionExA"
=> Fixed "error C4996: 'GetVersionExA': was declared deprecated" using a crutch.

rehlds/engine/net_ws.cpp
Only server can send them https://github.com/dreamstalker/rehlds/blob/c787546befd4c317f3759e341c1caabb9100719a/rehlds/engine/net_ws.cpp#L1341, so server can't receive them.
=> Removed split packets processing on the server socket

rehlds/engine/sv_main.cpp
That fixes a problem when texture file for model ends with "t.mdl", not "T.mdl"
=> Workaround for texture precaching on case-sensitive filesystem

rehlds/engine/sv_main.cpp
Typo from [this commit](https://github.com/dreamstalker/rehlds/commit/7891b6196a1fca7c984879e5ad3e9cce9d81f1e3).
Should we add `Q_strcmp` [there](https://github.com/dreamstalker/rehlds/commit/7891b6196a1fca7c984879e5ad3e9cce9d81f1e3#diff-462e3f794ed90c12c86f5d8d5b725c4aL4861) too?
=> Fixed typo in SV_FindModelNumbers

rehlds/build.gradle, rehlds/common/stdc++compat.cpp, rehlds/rehlds/public_amalgamation.cpp, shared_gcc.gradle, shared_icc.gradle
... and add compatibility tricks to avoid symbols with version GLIBCXX_3.4.16 and bigger.
=> Remove link statically with libstdc++

rehlds/engine/crc.cpp
[Click to get assembly listing](http://pastebin.com/MZFiAYfQ)
Instead of using cycle with multiple function calls, we make just one call.
=> Optimize MD5_Print function

rehlds/engine/net_ws.cpp, rehlds/engine/r_studio.cpp, rehlds/engine/sv_main.cpp
Found with cppcheck. They aren't 100% null dereferences, but can create dangerous situations in the future.
Inspect this calls:
1. [R_StudioCalcBonePosition](https://github.com/In-line/rehlds/blob/68fcac46e26f364f32f9220c4156a00f7bf7bbab/rehlds/engine/r_studio.cpp#L1097) `(adj == nullptr)`: 
2. [NET_LagPacket](https://github.com/In-line/rehlds/blob/3fd4e45420dfe754bb3bea4fa49d3f0bb62dbce6/rehlds/engine/net_ws.cpp#L1030) (most of params are null)
And [this line of code](https://github.com/In-line/rehlds/blob/558b1e367f10f1587e2fda401dae06bbf809fa09/rehlds/engine/sv_main.cpp#L4308)
=> Fix possible null dereferences

rehlds/HLTV/common/DemoFile.h, rehlds/HLTV/common/NetAddress.h, rehlds/common/TextConsoleWin32.h, rehlds/dedicated/src/precompiled.h, rehlds/game_shared/counter.h, rehlds/public/rehlds/osconfig.h, rehlds/rehlds/jitasm.h
Add WIN32_LEAN_AND_MEAN for prevent tons of unused windows definitions from headers.
=> Add WIN32_LEAN_AND_MEAN

dep/cppunitlite/src/Assertions.cpp
gcc version
```
user@user-pc ~/Desktop/programms/rehlds $ gcc --version
gcc (Ubuntu 6.2.0-5ubuntu12) 6.2.0 20161005
```
icc version:
```
user@user-pc ~/Desktop/programms/rehlds $ icc --version
icc (ICC) 17.0.1 20161005
```
```
/home/user/Desktop/programms/rehlds/dep/cppunitlite/src/Assertions.cpp(60): error: more than one instance of overloaded function "abs" matches the argument list:
function "abs(int)"
function "std::abs(long long)"
function "std::abs(long)"
argument types are: (double)
if (abs(expected - actual) > epsilon) {
```
=> Fix compilation under linux with ICC 17 (GCC 6.2)

rehlds/engine/tmessage.cpp
By default IsWhiteSpace do not check all whitespace characters.
HLDS behavior:
- ' '	(0x20)	space (SPC)
- '\t'	(0x09)	horizontal tab (TAB)
- '\n'	(0x0a)	newline (LF)
- '\r'	(0x0d)	carriage return (CR)
Added:
- '\f'	(0x0c)	feed (FF)
- '\v'	(0x0b)	vertical tab (VT)
For more info: http://www.cplusplus.com/reference/cctype/isspace/
=> Fix IsWhiteSpace

rehlds/build.gradle, version_script.lds
I tested this a little bit seems to not break AMX Mod X Hamsandwich module.
This reduced size of engine_i486.so by ~0.6 megabytes. 
Info about `--gc-sections`: https://stackoverflow.com/questions/6687630/how-to-remove-unused-c-c-symbols-with-gcc-and-ld
Info about version script: alliedmodders/amxmodx#447
Credits: @WPMGPRoSToTeMa, @s1lentq
=> Optimize size by removing unused data and functions

shared_gcc.gradle, shared_icc.gradle
After #527 strip removes all function names, which is actually pretty bad for debugging.
Credits: @s1lentq
=> Set stripSymbolTable to false

rehlds/engine/sv_main.cpp
Assume two clients connect with the following string
```connect 48 12345678  \prot\2\unique\-1\raw\261578371d95a424925835ca44f82811   \cl_lw\1\cl_lc\1\*hltv\1\rate\10000\cl_updaterate\20\hspecs\0\hslots\0\hdelay\30\name\test"```
Name will be parsed as ```test"```
Then in ```SV_CheckForDuplicateNames```, ```Info_SetValueForKey``` will fail because of the quotes, and an infinite loop will occur.
I also added a check for ```\```. Altough it's technically impossible to appear, it never hurts to be extra careful with this kind of client input.
TODO (by others, sorry, really busy atm):
- Fix ```COM_Parse``` so that you can't inject quote marks. Other exploits may currently exist that also rely on this bug.
=> Fix (Re)HLDS exploit (Can't use keys or values with a ")

rehlds/HLTV/Console/build.gradle, rehlds/HLTV/Console/msvc/Console.vcxproj, rehlds/HLTV/Console/msvc/Console.vcxproj.filters, rehlds/HLTV/Console/src/System.cpp, rehlds/HLTV/Console/src/precompiled.h, rehlds/common/minidump.cpp, rehlds/common/minidump.h, rehlds/dedicated/build.gradle, rehlds/dedicated/msvc/dedicated.vcxproj, rehlds/dedicated/msvc/dedicated.vcxproj.filters, rehlds/dedicated/src/precompiled.h, rehlds/dedicated/src/sys_window.cpp
Kinda hard to debug issues without crash dumps on hands.  Add crash dumps writing support on Windows. Makes resolving issues like https://github.com/dreamstalker/rehlds/issues/523, https://github.com/dreamstalker/rehlds/issues/698, https://github.com/dreamstalker/rehlds/issues/699 easier.
Crash dump is written to file in the same directory as crashed executable.  Crash dump file name format: `<exe name>_<app version>_crash_<date YYYYMMDD>_<time HHMMSS>_<unique counter>.mdmp`
for example, `hlds_3.6.0.675-dev+m_crash_20190702_005019_1.mdmp`
Command line option `-nominidumps` disables mini dump writing facility (same behavior as in Source games). Also, mini dumps are not written when debugger is attached.
Uses `DbgHelp.dll` to write minidumps, should be present on all Windows versions, but …
=> Catch crashes and write minidumps on windows

README.md, rehlds/engine/sv_main.cpp
Now if sv_use_entity_file set to 1, don't create new .ent files, use only exist.
=> Small update sv_use_entity_file

rehlds/public/tier0/dbg.h
warning C4996: _vsnprintf': This function or variable may be unsafe. Consider using _vsnprintf_s instead.
=> Fix _vsnprintf on windows

rehlds/engine/cmd.cpp
Cbuf_Execute doesn't ignore commented out string in case when string contains separator character `;` inside commented out string.
1. Config file `test.cfg` contains 
>// ; echo "test: commented out string"
2. Execute `exec test.cfg`
3. The text will printed in the console.
=> Cbuf_Execute: Add checks commented out for multi-lines.

rehlds/engine/sys_dll.cpp, rehlds/engine/sys_dll.h, rehlds/public/rehlds/rehlds_api.h, rehlds/rehlds/rehlds_api_impl.cpp, rehlds/rehlds/rehlds_api_impl.h, rehlds/version/version.h
I got the request to add the hookchain for `GetEntityInit`, so this PR just adds it, nothing more, nothing less. 😛 
Fixes #722.
Signed-off-by: Karol Szuster <karolsz9898@gmail.com>
=> Add GetEntityInit hook

README.md, rehlds/engine/server.h, rehlds/engine/sv_main.cpp, rehlds/engine/sv_user.cpp
| CVar | Def. value | Description | 
|:--|:--:|:--|
| sv_usercmd_custom_random_seed | 0 | When enabled server will populate an additional random seed independent of the client. | 
Ported from [CS:GO leaked source code](https://github.com/perilouswithadollarsign/cstrike15_src/blob/f82112a2388b841d72cb62ca48ab1846dfcc11c8/game/server/player.cpp#L3719)
Thanks to `danil.nesvetaev` for the reminder of this functionality in CS:GO. 👍
=> Add new CVar `sv_usercmd_custom_random_seed`

rehlds/engine/net_chan.cpp
Issue related to #888 is that, what we can't call SV_DropClient for another client inside callback while handling incoming network messages,
because call chains are `SV_DropClient -> Netchan_Clear -> Netchan_ClearFragments -> Netchan_FlushIncoming -> msg_readcount` cause clearing `msg_readcount` and `net_message` for all.
```
- SV_ConnectClient PRE  (id 1) net_message[msg_readcount] - there is something to read here
- SV_ConnectClient 3rd party   call SV_DropClient (id 2) -> msg_readcount = 0
- SV_ConnectClient POST (id 1) net_message[msg_readcount] - we have nothing left to read for this client, steam ticket is empty
```
Every incoming message initializes these global variables, so do we really need to clean them up while flushing?
=> Netchan_FlushIncoming: Don't clear global buffer of incoming network messages

rehlds/engine/world.cpp
Considered a heavy function, SV_ClipToLinks is called almost every frame where things "move". Since a fix done in the pfnShouldCollide function (#46) this function can be used safely, but in the context given, it wastes a lot of checks.
pfnShouldCollide is used by mods to filter entity collision from one to another, by allowing to NOT collide (but not to force collision), but just after this is called, some basic physics stuff is called to detect collision each other, having by result an useless call of pfnShouldCollide before. 
https://github.com/dreamstalker/rehlds/blob/de3679f0391f1452532c820f07a8c4042b1c4281/rehlds/engine/world.cpp#L1193-L1223
(like, checking they are far each other, why I'm checking collision on two distant entities?)
This PR moves pfnShouldCollide check after all …
=> Improve pfnShouldCollide condition on SV_ClipToLinks

rehlds/engine/pr_cmds.cpp, rehlds/engine/server.h, rehlds/engine/sv_main.cpp
Allows to work with HL25 server DLL, which acquires this new cvar and doesn't check against `nullptr`.
Was adding HL25 compatibility to Xash3D FWGS and decided to send this patch here too.
=> engine: add sv_allow_autoaim cvar for HL25 DLL compatibility

README.md, rehlds/engine/net_chan.cpp
This PR enhance security by controlling the decompression of incoming network data buffer to avoid server hangs and another potential risks associated with zip bomb attacks.
Added network security CVars:
- `sv_net_incoming_decompression` (0-1) Enables or disables incoming data decompression. Default: 1
- `sv_net_incoming_decompression_max_ratio` (0.0 - 100.0) Sets max allowed ratio between compressed and decompressed data. (A ratio close to 90 indicates large uncompressed data with low entropy, this means abnormal compressed data which can cause server to hang). Default: 80
- `sv_net_incoming_decompression_max_size` (16-65536) Adjusts max size in bytes of output data after decompression. Default: 65536
- `sv_net_incoming_decompression_punish` Time in minutes for which the player will be …
=> Implemented reduction of impact caused by zip-bomb exploit

.github/workflows/build.yml
❌ /__e/node20/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version 'GLIBC_2.28' not found (required by /__e/node20/bin/node)
=> Workflows: fix linux build(Action Checkout)

rehlds/engine/sv_user.cpp
=> Small fix in sv_user.cpp

.github/workflows/build.yml
This pull request introduces several key changes to improve the CI pipeline in the `rehlds` repository, addressing compatibility issues, standardizing CI processes, and optimizing artifact handling.
- **Node.js Compatibility Issue Resolution**  
- Updated action versions and dependencies to run on `*-latest` OS versions, fixing failures caused by outdated Node.js versions incompatible with legacy actions. Updated container configurations for build and test demos to match this requirement.
- **Action Updates**  
- Upgraded the `checkout` action to version 4 and `upload-artifact`/`download-artifact` actions to version 4 for more consistent and secure artifact management.
- **Demo Testing Enhancements**  
- Migrated to `ubuntu-latest` for demo tests and updated the container to …
=> CI Workflow Improvements and Fixes

rehlds/engine/net_ws.cpp
- Placed annoying messages under the `-dev` startup argument. (debug message)
=> `IP` and `IPX` allocation warnings move under `-dev` arg

.github/workflows/build.yml, README.md
-------------
> [!CAUTION]  
> This is `infrastructure` update! **NO** code and  **NO** bugfixes was implemented at `ReHLDS` at this PR.
-------------
Also, I know that we have .rc files that are used to create binaries.
The problem is that we have not yet fully decided how their future will develop from a development point of view. Also, now there are only 2 .rc files that are built into hlds.exe and hltv.exe. All other dlls are built naked, which excites antiviruses.
For now, I have chosen to use [rcedit](https://github.com/electron/rcedit), written by the Electron project, which can successfully read and edit resources in compiled files. Which is what I am actually doing.
For now, I suggest leaving it as is. To launch the mechanism. And optimize it in subsequent iterations of …
=> Added codesign and resources

rehlds/engine/info.cpp
This is a new exploit that was first mentioned in this issue - https://github.com/rehlds/ReHLDS/issues/1073
By using invalid utf8 chars in userinfo, an attacker can interrupt the reading of the string in `svc_updateuserinfo` for all connected clients, which will likely cause them to disconnect from the server due to incorrect reading of the rest of the packet. However, in addition to simply disconnecting clients, an attacker can append arbitrary network traffic to his userinfo, which connected clients can process. For example, in the PoC video below, an attacker compromises the `svc_stufftext` message, which executes some commands/cvars in the console of other clients:
https://www.youtube.com/watch?v=BIG7I859_aI
The thing is that when processing userinfo via the `setinfo` command, the …
=> Fix arbitrary network data sending exploit via malformed userinfo

rehlds/rehlds/rehlds_messagemngr_impl.cpp
Message Manager needs to support more than 16 parameteres to handle for example SVC_TEMPENTITY/TE_BEAMPOINTS.
I've increased the number of parameters to 32.
=> Message Manager fix -- increase the number of parameters

rehlds/engine/mathlib_sse.cpp
Fixed simd-function VectorCompare which had undefined behavior with -flto=full flag enabled while compiling via Clang
Also maybe this bug could be reproduced with others math fucntions. Need to investigate it further
=> Fix VectorCompare func while compiling with clang with -flto=full flag enabled

rehlds/engine/info.cpp
This PR introduces validation in [`Info_SetValueForStarKey()`](https://github.com/rehlds/ReHLDS/blob/58da97789f3c924dc703bd590f10f5c4a3644543/rehlds/engine/info.cpp#L556-L648) to reject user info keys and values containing ASCII control characters (such as newlines), addressing crashes triggered by malformed user info strings.
A malicious actor was detected sending a user info string with a model name containing `\r` (carriage return) or `\n` (line feed) characters, which triggers assertion failures in Windows clients. This led to clients aborting the game or repeatedly hitting the assertion, making ignoring an unacceptable choice.
* Adds a check to reject ASCII control characters in both keys and values of user info.
=> fix(userinfo): prohibit ASCII control characters in keys and values
